### PR TITLE
Fixing Duplicate headers

### PR DESCRIPTION
**Pull request by Atharva321**
Fixing double Headers  

Signed-off-by: Atharva Patil <yatinchaudhari8254@gmail.com>

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Hi, @Atharva321! Thanks - can you please sign your commits for the DCO? Instructions are here: https://github.com/openservicemesh/osm-docs/pull/25/checks?check_run_id=2569823442

**Comment by bridgetkromhout** [comment]
Thanks for signing. We now have another thing we need to fix - you are including commits unrelated to your PR (as you can see in https://github.com/openservicemesh/osm-docs/pull/25/files). If you aren't sure how to remove those, that is okay - you could close this PR and open another one with only your commits in it. Otherwise you can adjust this PR so you only have your commits. Thanks.

**Comment by Atharva321** [comment]
Adjusted PR

**Review by bridgetkromhout — APPROVED** [review]
Thanks!

**Pull request merged**
