### PR TITLE
docs(content/docs/guides/*): update left nav order and titles

### PR DESCRIPTION
**Pull request by zr-msft**
Change order and wording of doc titles in left nav for better
findability

docs(themes/dosmy/layouts/partials/sidebar-tree.html): change display
logic of left nav

Updated display logic to expand tree for active items only. This
allows for a cleaner display and makes it easier to navigate.

Signed-off-by: Zach Rhoads <zachary.rhoads@microsoft.com>

### CODE REVIEW

**Comment by zr-msft** [comment]
FYI, i'm aware of the rendering bug at the top level of the site where the left nav is not shown. Working on it

**Review by shashankram — CHANGES_REQUESTED** [review]
This seems buggy:
image

**Comment by jaellio** [comment]
I like this change! Should it be possible to expand multiple menus at the same time?

**Comment by SanyaKochhar** [comment]
Looks good! Just wondering if it's possible to add `>` next to list items that expand into further menus? Not necessary but I think it would be a good addition for clarity

image

**Comment by zr-msft** [comment]
thank you @bridgetkromhout @SanyaKochhar  and @jaellio for the feedback!

ATM, the menu is not really interactive (e.g. expand/contract nested items) so that would be something net-new we'd have to add.

From a style perspective, i like the idea of adding visual indicators indicating if there are child nodes. I explored doing this, but i wasn't able to find where that functionality actually is. 

I'm happy to capture both of those items to explore in a future update. Does that work for you all?

**Review by jaellio — APPROVED** [review]

**Comment by jaellio** [comment]
LGTM. If they don't exist, could you create issues to track the work to make the menu interactive and add visual indicators for child nodes?

**Review by jaellio — APPROVED** [review]

**Comment by zr-msft** [comment]
Thank you @jaellio I'll capture those requests in an issue. I have done some research on the scrolling issue, but there wasn't an easy way that i found to address it.

**Review by shashankram — APPROVED** [review]

**Pull request merged**
