### PR TITLE
Fixing Broken links and removing double headers

### PR DESCRIPTION
**Pull request by Atharva321**
Fixing broken links of interfaces page and removed double headers headers Observability and OSM Manual Demo Guide .

Signed-off-by: Atharva321 <atharvapatil19202@gmail.com>

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
Thanks! For links inside the website, you can remove the `https://docs.openservicemesh.io` part of the url and just have it start with `/docs` - that way, the pages will also look correct in the Netlify previews.

**Comment by Atharva321** [comment]
ok

**Comment by bridgetkromhout** [comment]
Hi, you will also need to sign-off on the new commit, for the DCO: https://github.com/openservicemesh/osm-docs/pull/41/checks?check_run_id=2587410600

**Comment by Atharva321** [comment]
Yes  done

**Review by bridgetkromhout — APPROVED** [review]
Thanks!

**Pull request merged**
