### PR TITLE
align docs with upcoming single provider change

### PR DESCRIPTION
**Pull request by steeling**

### CODE REVIEW

**Review by shashankram — CHANGES_REQUESTED** [review]
Please do not make this change till the implementation is finalized and complete in the osm repo. Thanks

**Comment by zr-msft** [comment]
@steeling is this PR still valid? Linked PR was closed without merging. If not valid, do you mind closing this PR?

**Comment by zr-msft** [comment]
@steeling is this PR still valid? Linked PR was closed without merging. If not valid, do you mind closing this PR?

**Comment by steeling** [comment]
I'll close and re-open when this is done

**Pull request closed without merging**
